// Generated by gencpp from file object_msgs/Object.msg
// DO NOT EDIT!


#ifndef OBJECT_MSGS_MESSAGE_OBJECT_H
#define OBJECT_MSGS_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_msgs
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : class_name()
    , xmin_ymin_xmax_ymax()  {
    }
  Object_(const ContainerAllocator& _alloc)
    : class_name(_alloc)
    , xmin_ymin_xmax_ymax(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _xmin_ymin_xmax_ymax_type;
  _xmin_ymin_xmax_ymax_type xmin_ymin_xmax_ymax;





  typedef boost::shared_ptr< ::object_msgs::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_msgs::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::object_msgs::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::object_msgs::Object > ObjectPtr;
typedef boost::shared_ptr< ::object_msgs::Object const> ObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_msgs::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_msgs::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_msgs::Object_<ContainerAllocator1> & lhs, const ::object_msgs::Object_<ContainerAllocator2> & rhs)
{
  return lhs.class_name == rhs.class_name &&
    lhs.xmin_ymin_xmax_ymax == rhs.xmin_ymin_xmax_ymax;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_msgs::Object_<ContainerAllocator1> & lhs, const ::object_msgs::Object_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::object_msgs::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::Object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::Object_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9beacd4cdb37d3951c7c33ecebfabd1";
  }

  static const char* value(const ::object_msgs::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9beacd4cdb37d39ULL;
  static const uint64_t static_value2 = 0x51c7c33ecebfabd1ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_msgs/Object";
  }

  static const char* value(const ::object_msgs::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string class_name\n"
"uint32[] xmin_ymin_xmax_ymax\n"
;
  }

  static const char* value(const ::object_msgs::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_msgs::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.class_name);
      stream.next(m.xmin_ymin_xmax_ymax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_msgs::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_msgs::Object_<ContainerAllocator>& v)
  {
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
    s << indent << "xmin_ymin_xmax_ymax[]" << std::endl;
    for (size_t i = 0; i < v.xmin_ymin_xmax_ymax.size(); ++i)
    {
      s << indent << "  xmin_ymin_xmax_ymax[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.xmin_ymin_xmax_ymax[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_MSGS_MESSAGE_OBJECT_H
