// Generated by gencpp from file object_msgs/ObjectArray.msg
// DO NOT EDIT!


#ifndef OBJECT_MSGS_MESSAGE_OBJECTARRAY_H
#define OBJECT_MSGS_MESSAGE_OBJECTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <object_msgs/Object.h>

namespace object_msgs
{
template <class ContainerAllocator>
struct ObjectArray_
{
  typedef ObjectArray_<ContainerAllocator> Type;

  ObjectArray_()
    : Objects()  {
    }
  ObjectArray_(const ContainerAllocator& _alloc)
    : Objects(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::object_msgs::Object_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::object_msgs::Object_<ContainerAllocator> >> _Objects_type;
  _Objects_type Objects;





  typedef boost::shared_ptr< ::object_msgs::ObjectArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_msgs::ObjectArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectArray_

typedef ::object_msgs::ObjectArray_<std::allocator<void> > ObjectArray;

typedef boost::shared_ptr< ::object_msgs::ObjectArray > ObjectArrayPtr;
typedef boost::shared_ptr< ::object_msgs::ObjectArray const> ObjectArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_msgs::ObjectArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_msgs::ObjectArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_msgs::ObjectArray_<ContainerAllocator1> & lhs, const ::object_msgs::ObjectArray_<ContainerAllocator2> & rhs)
{
  return lhs.Objects == rhs.Objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_msgs::ObjectArray_<ContainerAllocator1> & lhs, const ::object_msgs::ObjectArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::object_msgs::ObjectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::ObjectArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::ObjectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::ObjectArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::ObjectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::ObjectArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_msgs::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a82955a978c818e847a2c852e8536db8";
  }

  static const char* value(const ::object_msgs::ObjectArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa82955a978c818e8ULL;
  static const uint64_t static_value2 = 0x47a2c852e8536db8ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_msgs::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_msgs/ObjectArray";
  }

  static const char* value(const ::object_msgs::ObjectArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_msgs::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Object[] Objects\n"
"================================================================================\n"
"MSG: object_msgs/Object\n"
"string class_name\n"
"uint32[] xmin_ymin_xmax_ymax\n"
;
  }

  static const char* value(const ::object_msgs::ObjectArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_msgs::ObjectArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_msgs::ObjectArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_msgs::ObjectArray_<ContainerAllocator>& v)
  {
    s << indent << "Objects[]" << std::endl;
    for (size_t i = 0; i < v.Objects.size(); ++i)
    {
      s << indent << "  Objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::object_msgs::Object_<ContainerAllocator> >::stream(s, indent + "    ", v.Objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_MSGS_MESSAGE_OBJECTARRAY_H
