//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the limo_mission package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __limo_mission__TRAFFICLIGHTCONFIG_H__
#define __limo_mission__TRAFFICLIGHTCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace limo_mission
{
  class TrafficLightConfigStatics;

  class TrafficLightConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(TrafficLightConfig &config, const TrafficLightConfig &max, const TrafficLightConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const TrafficLightConfig &config1, const TrafficLightConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, TrafficLightConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const TrafficLightConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, TrafficLightConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const TrafficLightConfig &config) const = 0;
      virtual void getValue(const TrafficLightConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T TrafficLightConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T TrafficLightConfig::* field;

      virtual void clamp(TrafficLightConfig &config, const TrafficLightConfig &max, const TrafficLightConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const TrafficLightConfig &config1, const TrafficLightConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, TrafficLightConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const TrafficLightConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, TrafficLightConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const TrafficLightConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const TrafficLightConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, TrafficLightConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, TrafficLightConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<TrafficLightConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(TrafficLightConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("red_h_low1"==(*_i)->name){red_h_low1 = boost::any_cast<int>(val);}
        if("red_h_high1"==(*_i)->name){red_h_high1 = boost::any_cast<int>(val);}
        if("red_h_low2"==(*_i)->name){red_h_low2 = boost::any_cast<int>(val);}
        if("red_h_high2"==(*_i)->name){red_h_high2 = boost::any_cast<int>(val);}
        if("red_s_low"==(*_i)->name){red_s_low = boost::any_cast<int>(val);}
        if("red_s_high"==(*_i)->name){red_s_high = boost::any_cast<int>(val);}
        if("red_v_low"==(*_i)->name){red_v_low = boost::any_cast<int>(val);}
        if("red_v_high"==(*_i)->name){red_v_high = boost::any_cast<int>(val);}
        if("green_h_low"==(*_i)->name){green_h_low = boost::any_cast<int>(val);}
        if("green_h_high"==(*_i)->name){green_h_high = boost::any_cast<int>(val);}
        if("green_s_low"==(*_i)->name){green_s_low = boost::any_cast<int>(val);}
        if("green_s_high"==(*_i)->name){green_s_high = boost::any_cast<int>(val);}
        if("green_v_low"==(*_i)->name){green_v_low = boost::any_cast<int>(val);}
        if("green_v_high"==(*_i)->name){green_v_high = boost::any_cast<int>(val);}
        if("min_area"==(*_i)->name){min_area = boost::any_cast<int>(val);}
        if("circularity_thresh"==(*_i)->name){circularity_thresh = boost::any_cast<double>(val);}
        if("roi_top"==(*_i)->name){roi_top = boost::any_cast<int>(val);}
        if("roi_bottom"==(*_i)->name){roi_bottom = boost::any_cast<int>(val);}
        if("roi_left"==(*_i)->name){roi_left = boost::any_cast<int>(val);}
        if("roi_right"==(*_i)->name){roi_right = boost::any_cast<int>(val);}
        if("brightness_factor"==(*_i)->name){brightness_factor = boost::any_cast<double>(val);}
      }
    }

    int red_h_low1;
int red_h_high1;
int red_h_low2;
int red_h_high2;
int red_s_low;
int red_s_high;
int red_v_low;
int red_v_high;
int green_h_low;
int green_h_high;
int green_s_low;
int green_s_high;
int green_v_low;
int green_v_high;
int min_area;
double circularity_thresh;
int roi_top;
int roi_bottom;
int roi_left;
int roi_right;
double brightness_factor;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int red_h_low1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int red_h_high1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int red_h_low2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int red_h_high2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int red_s_low;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int red_s_high;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int red_v_low;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int red_v_high;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int green_h_low;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int green_h_high;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int green_s_low;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int green_s_high;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int green_v_low;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int green_v_high;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_area;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double circularity_thresh;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int roi_top;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int roi_bottom;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int roi_left;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int roi_right;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double brightness_factor;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("TrafficLightConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const TrafficLightConfig &__max__ = __getMax__();
      const TrafficLightConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const TrafficLightConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const TrafficLightConfig &__getDefault__();
    static const TrafficLightConfig &__getMax__();
    static const TrafficLightConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const TrafficLightConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void TrafficLightConfig::ParamDescription<std::string>::clamp(TrafficLightConfig &config, const TrafficLightConfig &max, const TrafficLightConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class TrafficLightConfigStatics
  {
    friend class TrafficLightConfig;

    TrafficLightConfigStatics()
    {
TrafficLightConfig::GroupDescription<TrafficLightConfig::DEFAULT, TrafficLightConfig> Default("Default", "", 0, 0, true, &TrafficLightConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.red_h_low1 = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.red_h_low1 = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.red_h_low1 = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_h_low1", "int", 0, "Red H low 1", "", &TrafficLightConfig::red_h_low1)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_h_low1", "int", 0, "Red H low 1", "", &TrafficLightConfig::red_h_low1)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.red_h_high1 = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.red_h_high1 = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.red_h_high1 = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_h_high1", "int", 0, "Red H high 1", "", &TrafficLightConfig::red_h_high1)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_h_high1", "int", 0, "Red H high 1", "", &TrafficLightConfig::red_h_high1)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.red_h_low2 = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.red_h_low2 = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.red_h_low2 = 160;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_h_low2", "int", 0, "Red H low 2", "", &TrafficLightConfig::red_h_low2)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_h_low2", "int", 0, "Red H low 2", "", &TrafficLightConfig::red_h_low2)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.red_h_high2 = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.red_h_high2 = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.red_h_high2 = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_h_high2", "int", 0, "Red H high 2", "", &TrafficLightConfig::red_h_high2)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_h_high2", "int", 0, "Red H high 2", "", &TrafficLightConfig::red_h_high2)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.red_s_low = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.red_s_low = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.red_s_low = 100;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_s_low", "int", 0, "Red S low", "", &TrafficLightConfig::red_s_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_s_low", "int", 0, "Red S low", "", &TrafficLightConfig::red_s_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.red_s_high = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.red_s_high = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.red_s_high = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_s_high", "int", 0, "Red S high", "", &TrafficLightConfig::red_s_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_s_high", "int", 0, "Red S high", "", &TrafficLightConfig::red_s_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.red_v_low = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.red_v_low = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.red_v_low = 100;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_v_low", "int", 0, "Red V low", "", &TrafficLightConfig::red_v_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_v_low", "int", 0, "Red V low", "", &TrafficLightConfig::red_v_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.red_v_high = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.red_v_high = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.red_v_high = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_v_high", "int", 0, "Red V high", "", &TrafficLightConfig::red_v_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("red_v_high", "int", 0, "Red V high", "", &TrafficLightConfig::red_v_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.green_h_low = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.green_h_low = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.green_h_low = 35;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("green_h_low", "int", 0, "Green H low", "", &TrafficLightConfig::green_h_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("green_h_low", "int", 0, "Green H low", "", &TrafficLightConfig::green_h_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.green_h_high = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.green_h_high = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.green_h_high = 85;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("green_h_high", "int", 0, "Green H high", "", &TrafficLightConfig::green_h_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("green_h_high", "int", 0, "Green H high", "", &TrafficLightConfig::green_h_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.green_s_low = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.green_s_low = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.green_s_low = 23;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("green_s_low", "int", 0, "Green S low", "", &TrafficLightConfig::green_s_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("green_s_low", "int", 0, "Green S low", "", &TrafficLightConfig::green_s_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.green_s_high = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.green_s_high = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.green_s_high = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("green_s_high", "int", 0, "Green S high", "", &TrafficLightConfig::green_s_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("green_s_high", "int", 0, "Green S high", "", &TrafficLightConfig::green_s_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.green_v_low = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.green_v_low = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.green_v_low = 80;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("green_v_low", "int", 0, "Green V low", "", &TrafficLightConfig::green_v_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("green_v_low", "int", 0, "Green V low", "", &TrafficLightConfig::green_v_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.green_v_high = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.green_v_high = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.green_v_high = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("green_v_high", "int", 0, "Green V high", "", &TrafficLightConfig::green_v_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("green_v_high", "int", 0, "Green V high", "", &TrafficLightConfig::green_v_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_area = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_area = 10000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_area = 300;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("min_area", "int", 0, "Minimum detection area", "", &TrafficLightConfig::min_area)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("min_area", "int", 0, "Minimum detection area", "", &TrafficLightConfig::min_area)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.circularity_thresh = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.circularity_thresh = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.circularity_thresh = 0.6;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<double>("circularity_thresh", "double", 0, "Circularity threshold", "", &TrafficLightConfig::circularity_thresh)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<double>("circularity_thresh", "double", 0, "Circularity threshold", "", &TrafficLightConfig::circularity_thresh)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roi_top = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roi_top = 480;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roi_top = 200;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("roi_top", "int", 0, "ROI top", "", &TrafficLightConfig::roi_top)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("roi_top", "int", 0, "ROI top", "", &TrafficLightConfig::roi_top)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roi_bottom = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roi_bottom = 480;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roi_bottom = 350;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("roi_bottom", "int", 0, "ROI bottom", "", &TrafficLightConfig::roi_bottom)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("roi_bottom", "int", 0, "ROI bottom", "", &TrafficLightConfig::roi_bottom)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roi_left = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roi_left = 640;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roi_left = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("roi_left", "int", 0, "ROI left", "", &TrafficLightConfig::roi_left)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("roi_left", "int", 0, "ROI left", "", &TrafficLightConfig::roi_left)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roi_right = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roi_right = 640;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roi_right = 250;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("roi_right", "int", 0, "ROI right", "", &TrafficLightConfig::roi_right)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<int>("roi_right", "int", 0, "ROI right", "", &TrafficLightConfig::roi_right)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.brightness_factor = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.brightness_factor = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.brightness_factor = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<double>("brightness_factor", "double", 0, "Brightness factor (0.1-1.0, lower=darker)", "", &TrafficLightConfig::brightness_factor)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TrafficLightConfig::AbstractParamDescriptionConstPtr(new TrafficLightConfig::ParamDescription<double>("brightness_factor", "double", 0, "Brightness factor (0.1-1.0, lower=darker)", "", &TrafficLightConfig::brightness_factor)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(TrafficLightConfig::AbstractGroupDescriptionConstPtr(new TrafficLightConfig::GroupDescription<TrafficLightConfig::DEFAULT, TrafficLightConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<TrafficLightConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<TrafficLightConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<TrafficLightConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    TrafficLightConfig __max__;
    TrafficLightConfig __min__;
    TrafficLightConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const TrafficLightConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static TrafficLightConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &TrafficLightConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const TrafficLightConfig &TrafficLightConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const TrafficLightConfig &TrafficLightConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const TrafficLightConfig &TrafficLightConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<TrafficLightConfig::AbstractParamDescriptionConstPtr> &TrafficLightConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<TrafficLightConfig::AbstractGroupDescriptionConstPtr> &TrafficLightConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const TrafficLightConfigStatics *TrafficLightConfig::__get_statics__()
  {
    const static TrafficLightConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = TrafficLightConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __TRAFFICLIGHTRECONFIGURATOR_H__
